package dadacore.chatter

import dadacore.model.NextWordEntry

/** Sentence generated by [[dadacore.chatter.Chatter]]. Represents both text sentence and some internal model data
  * useful for classifying generated sentences.
  */
trait GeneratedSentence {
  /** Textual representation of generated sentence */
  def text:String

  /** Sequence of [[dadacore.model.NextWordEntry]] for each of words in this sentence. */
  def words:Seq[NextWordEntry[String]]
}
