package dadacore.text

/** Joins words generated by model into a string of text.
  *
  * Usually model (with String Word type) generates sequence of words as lowercase strings, both for words and
  * separators (spaces and punctuation). Joiners join such generated sequences of strings to ready to output string
  * of text.
  */
trait Joiner {
  def join(words:Seq[String]):String
}
